export const PROMPTS: string[] = [
  // Animals
  'flying elephant',
  'cat in a spacesuit',
  'ninja unicorn',
  'dog riding a bicycle',
  'penguin at the beach',
  'giraffe eating spaghetti',
  'bear playing guitar',
  'owl doing yoga',
  'shark in a bathtub',
  'squirrel bank robber',
  'dinosaur in an office',
  'frog prince',
  'snail racing car driver',
  'monkey astronaut',
  'turtle DJ',
  'hippo ballerina',
  'wolf cooking chef',
  'parrot lawyer',
  'cow superhero',
  'rabbit magician',

  // Food
  'spaghetti monster',
  'melting ice cream',
  'dancing cactus',
  'pizza delivery by jetpack',
  'taco in a tuxedo',
  'burger skyscraper',
  'donut lifeguard',
  'sushi samurai',
  'waffle house on fire',
  'hot dog parade',
  'grumpy broccoli',
  'evil strawberry',
  'banana split competition',
  'popcorn party',
  'noodle soup swimming pool',
  'cheese moon',
  'carrot rocket',
  'cupcake army',
  'pretzel yoga pose',
  'lollipop forest',

  // Activities
  'wizard riding a skateboard',
  'robot eating pizza',
  'time traveling toaster',
  'astronaut grocery shopping',
  'zombie going to school',
  'pirate at a car wash',
  'knight playing video games',
  'caveman using smartphone',
  'superhero doing laundry',
  'mermaid driving a truck',
  'vampire at the dentist',
  'witch ordering coffee',
  'skeleton doing taxes',
  'ghost writing a novel',
  'alien learning to drive',

  // Objects
  'giant rubber duck',
  'dancing cactus',
  'umbrella rebellion',
  'haunted refrigerator',
  'sentient vending machine',
  'angry alarm clock',
  'couch potato literally',
  'teleporting mailbox',
  'self-driving shopping cart',
  'magic carpet traffic jam',
  'invisible chair',
  'telescope for ants',
  'sentient vacuum cleaner',
  'rebellious toaster',
  'world\'s tallest sandwich',

  // Fantasy
  'dragon in a library',
  'elf programmer',
  'gnome stock trader',
  'mermaid at the gym',
  'centaur traffic cop',
  'goblin barista',
  'phoenix firefighter',
  'troll bridge builder',
  'fairy tax accountant',
  'kraken knitting club',
  'unicorn mechanic',
  'dwarf hairdresser',
  'orc pastry chef',
  'leprechaun day trader',
  'chimera pet groomer',

  // Science
  'black hole vacuum cleaner',
  'DNA double helix jump rope',
  'robot falling in love',
  'time machine made of cardboard',
  'gravity failure at the mall',
  'scientist testing invisible ink',
  'clone factory mix-up',
  'robot pet dog',
  'quantum physics homework',
  'laboratory experiment gone wrong',

  // Misc funny
  'office chair race',
  'bread winning election',
  'paper airplane war',
  'blanket fort architect',
  'competitive leaf blowing',
  'professional pillow fight',
  'extreme ironing',
  'synchronized swimming for dogs',
  'yoga class for robots',
  'speed knitting championship',
];

export function getRandomPrompts(count: number): string[] {
  const shuffled = [...PROMPTS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export default PROMPTS;
